-- AlterTable
ALTER TABLE "User" ADD COLUMN "activityLevel" TEXT;
ALTER TABLE "User" ADD COLUMN "age" INTEGER;
ALTER TABLE "User" ADD COLUMN "gender" TEXT;
ALTER TABLE "User" ADD COLUMN "goal" TEXT;
ALTER TABLE "User" ADD COLUMN "height" INTEGER;
ALTER TABLE "User" ADD COLUMN "weight" INTEGER;
